source "https://rubygems.org"

gem 'sinatra', '~> 1.4.6'
gem 'sinatra-contrib', '~> 1.4.2', require: false
gem 'sinatra-r18n', '~> 2.0.3'

gem 'mongoid', '~> 4.0.1'

gem 'rufus-scheduler', '~> 3.0.9'

group :test, :development do
  gem 'pry', '~> 0.10.1'
  gem 'pry-stack_explorer', '~> 0.4.9.2'
  gem 'pry-byebug', '~> 3.1.0'
end

group :test do
  gem 'rspec', '~> 3.2.0'
  gem 'ci_reporter_rspec', '~> 1.0.0'
  gem 'simplecov', '~> 0.9.2', :require => false
  gem 'simplecov-rcov', '~> 0.2.3', :require => false
end
