source "https://rubygems.org"

gem 'thin'

gem 'sinatra'
gem 'sinatra-contrib', require: false
gem 'sinatra-r18n'

group :test, :development do
  gem 'pry'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
end

group :test do
  gem 'rspec'
  gem 'ci_reporter_rspec'
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
end
